In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.decomposition import PCA
import joblib

In [51]:
df = pd.read_csv("data/loan_prediction_dataset.csv")
df

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Loan_Approved
0,56,81788,334,15022,48,Employed,0
1,69,102879,781,21013,24,Self-Employed,1
2,46,58827,779,39687,60,Self-Employed,0
3,32,127188,364,16886,24,Unemployed,0
4,60,25655,307,26256,36,Unemployed,0
...,...,...,...,...,...,...,...
1995,63,87580,761,29716,48,Employed,1
1996,67,27368,695,13601,36,Employed,0
1997,69,105436,636,37018,36,Self-Employed,0
1998,24,116136,441,9061,48,Employed,0
1999,20,66403,616,9609,12,Unemployed,0

In [52]:
le = LabelEncoder()
df["Employment_Status"] = le.fit_transform(df["Employment_Status"])
df

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Loan_Approved
0,56,81788,334,15022,48,0,0
1,69,102879,781,21013,24,1,1
2,46,58827,779,39687,60,1,0
3,32,127188,364,16886,24,2,0
4,60,25655,307,26256,36,2,0
...,...,...,...,...,...,...,...
1995,63,87580,761,29716,48,0,1
1996,67,27368,695,13601,36,0,0
1997,69,105436,636,37018,36,1,0
1998,24,116136,441,9061,48,0,0
1999,20,66403,616,9609,12,2,0

In [53]:
X = df.drop(columns = ["Loan_Approved"])
y = df["Loan_Approved"]

In [54]:
pca = PCA(n_components = 5)
X = pca.fit_transform(X)

In [55]:
pca.explained_variance_ratio_

array([8.77472737e-01, 1.22511714e-01, 1.52351713e-05, 1.77681754e-07,
       1.36283702e-07])

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [57]:
mlp = MLPClassifier()
scores = cross_val_score(mlp, X_train, y_train, cv = 10, scoring = "accuracy")
scores.mean()

np.float64(0.9431249999999999)

In [58]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100),activation='relu', learning_rate='adaptive', max_iter=1000, alpha=0.0001, random_state=42)
scores = cross_val_score(mlp, X_train, y_train, cv = 10, scoring = "accuracy")
scores.mean()

np.float64(0.8843750000000001)